### PR TITLE
Fixing windows & babel-node

### LINKED ISSUE #57: spawn error on startup (Windows 7)
I totally understand if Windows isn't really supported yet, but thought I'd give you a heads up that I'm hitting an issue upon startup.

**With this run script:**
```js
"scripts": {
    "dev": "webpack-dashboard -- webpack-dev-server --config ./webpack.dev.js"
}
```

**And this in my webpack plugins:**
```js
plugins: [
    new DashboardPlugin()
]
```

**I get the following error:**
```bash
> webpack-dashboard -- webpack-dev-server --config ./webpack.dev.config.js

Error: spawn webpack-dev-server ENOENT
    at exports._errnoException (util.js:1007:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:160:18)
    at node.js:456:3

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev:app"
npm ERR! node v6.2.1
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
```

### LINKED ISSUE #61: Quitting webpack-dashboard doesn't kill server
When I launch `webpack-dashboard` the first time, everything works great. But when I quit by pressing `q`, then try to relaunch it, I get `Error: listen EADDRINUSE :::3000`. Browsing to my app confirms that the server `webpack-dashboard` launched the first time is still running, and can only be killed by tracking down the rogue process.

My setup, on OS X with `webpack-dashboard@0.1.1`:

In `package.json`:

```
"start:dev": "webpack-dashboard -- babel-node src/server.js"
```

In `src/server.js`:

```js
if (app.get('env') === 'development') {
  const config = require('../webpack.config.babel')
  const compiler = require('webpack')(config)
  const DashboardPlugin = require('webpack-dashboard/plugin')
  compiler.apply(new DashboardPlugin())
  app.use(require('webpack-dev-middleware')(compiler, {
    publicPath: config.output.publicPath,
    quiet: true
  }))
  app.use(require('webpack-hot-middleware')(compiler, {
    log: () => {}
  }))
}
```

### PR DESCRIPTION
**Pull request by kenwheeler**
- Fixes windows by using cross-spawn, closes #57, #62
- Fixes babel node issue where child processes aren't killed, closes #61

cc @exogen @ryan-roemer Does this seem reasonable?

### CODE REVIEW

**Comment by exogen** [comment]
👍

**Comment by jing2si** [comment]
window 10

**Comment by jaylaw81** [comment]
Looking forward to this fix, half our team is on Windows and experience this issue

**Comment by kenwheeler** [comment]
@jaylaw81 trying to fix output color before cutting a release.

**Pull request merged**
