### PR TITLE
Add timer section, that shows how much time it took to compile

### PR DESCRIPTION
**Pull request by Wobbly-Wibbly**
Add a timer section http://imgur.com/XywNYC5
https://github.com/FormidableLabs/webpack-dashboard/issues/24

### CODE REVIEW

**Comment by kenwheeler** [comment]
I wonder if we should add this to the Operations box like "Finished (in 2s)", instead of creating a new box. thoughts?

**Comment by Wobbly-Wibbly** [comment]
idle (finished in 22s)
823/1423 build modules (running for 12s)

Something like this? yes?

**Comment by kenwheeler** [comment]
Sure, maybe just show the time value, so that it doesn't crunch too much on resize. Can you also do before and after benchmarks, so I can see what kind of overhead this adds to the build process?

**Comment by Wobbly-Wibbly** [comment]
It took 59944/57230/56527/57998 milliseconds with my changes for my project.
57200/60059/56461/57793 without

**Comment by kenwheeler** [comment]
Seems legit

**Comment by moretti** [comment]
+1

We get this from the bundle stats:

```.js
compiler.plugin('done', stats => {
  console.log(`${stats.hash} built in ${stats.endTime - stats.startTime} ms`);
});
```

**Comment by Wobbly-Wibbly** [comment]
Do you mean that it should be shown only `done` ?
I'm updating time in handler of the "progress plugin" and as I know there is no start available :(

**Comment by moretti** [comment]
Oh, sorry, I didn't realize that :)
```
823/1423 build modules (running for 12s)
```
Yeah, I don't see either any better way of doing that.
Looks good!

**Pull request merged**
