### PR TITLE
console redirection

### LINKED ISSUE #12: The log is over of the panel
Firstly, thanks this awesome tool 👍 . Anyway, I run up webpack-dashboard successfully, but got some  layout over.

Like following, there's some warning text may too long so that it over the panel(First line).
Before broken

Maybe a hidden text or scroll is better solution for this issue.
Thanks :)

### PR DESCRIPTION
**Pull request by kenwheeler**
This should fix #12

### CODE REVIEW

**Comment by jonstuebe** [comment]
@kenwheeler  👍🏼

**Comment by JesseObrien** [comment]
The only thing I would say to add is a way to turn this off somehow? Just in case you want to get access back to the real console.
👍

**Comment by kenwheeler** [comment]
Do you think I should redefine on the global object? like `global.oldConsole`, or just expose the unhook?

**Comment by JesseObrien** [comment]
Hmm. Not sure, I don't know enough about these things to be commenting probably, I usually let the professionals handle it 💃

**Comment by eliperelman** [comment]
Tested this patch out, works well for me. I started the webpack-dev-server, then just did a console log using the tagged strings:

```js
server.listen(port, host, () => console.log(`{green-fg}Dev server started on:{/} ${schema}://${host}:${port}`));
```

screenshot

**Comment by kenwheeler** [comment]
Alright. Bringing my daughter to the beach, when I get back later I just want to colorize errors and warns, and support multiple arg logging and then i'm gonna merge this and cut a release. Overriding console feels inevitable, so whatevs.

**Comment by eliperelman** [comment]
Note that your interception of `console` methods won't work in cases where someone is writing to stdout or stderr like `process.stdout.write('...')`. You could use something like [intercept-stdout](https://www.npmjs.com/package/intercept-stdout) to handle that, as well as avoiding having to do the capturing work yourself.

**Comment by kenwheeler** [comment]
I tried that and it actually didn't get any of the consoles but instead printed a ton of noise from the cursor output

**Comment by crisu83** [comment]
Awesome, just what I was looking for! 👍

**Comment by graingert** [comment]
@kenwheeler you could fix stdout wrapping if you used a subprocess to run webpack in: https://github.com/FormidableLabs/webpack-dashboard/issues/30

**Comment by kenwheeler** [comment]
@graingert would that work for folks using the webpack-dev-server command though?

**Comment by graingert** [comment]
@kenwheeler sure, you'd just do:
```shell
webpack-dashboard -- webpack-dev-server <args>
```

**Comment by kenwheeler** [comment]
So right now the API has you create a dashboard instance, and then add a plugin to a webpack config that calls the `.setData` method on that instance. How does that work with the above? Genuinely trying to understand, I'm no node superstar and it feels like this modification needs to happen.

**Comment by graingert** [comment]
when you spawn a node subprocess from node, the child gets a process.send() method:

https://nodejs.org/api/process.html#process_process_send_message_sendhandle_options_callback

You can spawn webpack-dev-server, then capture its stdout with a pipe, then in a Plugin all you need to do is send data that you need in Dashboard down "process.send()" then receive it in https://nodejs.org/api/child_process.html#child_process_event_message childProcess.on('message', cb);

**Comment by kenwheeler** [comment]
So inside the plugin I would write to stdout?

**Comment by kenwheeler** [comment]
Oh, I'd use process send

**Comment by graingert** [comment]
@kenwheeler you'd let the webpack or whatever people want write to stdout (no more --quiet etc) then you'd push what you need with "process.send()"

**Comment by kenwheeler** [comment]
Sounds like I have a hell of an evening ahead of me

**Comment by graingert** [comment]
then the only config would be, hey add this plugin, then run `webpack-dashboard -- whatever-runs-your-wp-build`

**Comment by kenwheeler** [comment]
so I could run something like `webpack-dashboard -- npm run dev` and that'd work fine?

**Comment by graingert** [comment]
I don't think so, because npm boots another child process

**Comment by graingert** [comment]
but you could set and export an environment variable with a unix/tcp/named-pipe that your plugin could use, instead of process.send()

**Comment by kenwheeler** [comment]
How would it work with the express based dev server approach?

**Comment by kenwheeler** [comment]
Would you just pass the file path?

**Comment by graingert** [comment]
if you used the `export environment variable with a unix socket/windows pipe thing in` approach you could use:
```js
webpack-dashboard -- node ./path/to/server/app.js
```

wepack-dashboard would create a unix socket, and put it in _WEBPACK_DASHBOARD, then webpack-dashboard/plugin would look for _WEBPACK_DASHBOARD and connect to the socket it describes

**Comment by kenwheeler** [comment]
And that approach doesn't require workers?

**Comment by graingert** [comment]
well all the workers library does is wrap up the `subprocess/process.send()` API in something that works with WebWorkers code

**Pull request merged**
