### PR TITLE
min+gz sizes using inspectpack

### PR DESCRIPTION
**Pull request by tptee**
Depends on https://github.com/FormidableLabs/inspectpack/pull/24 + a future PR upstream

Replaces the old module output with a min+gz/% display of each library in each bundle using inspectpack in a child process. Also merges min+gz full bundle sizes into the assets list (still maintains original sizes for non-js assets).

screen shot 2017-03-31 at 3 48 38 pm

Questions:
- Since `inspectpack` takes some time to minify/gzip each module, there's a noticeable lag between webpack build completion and module size output. It's not blocking, since `inspectpack` runs in a child process, but it's definitely weird. Given that, do we want to add a progress bar for module sizes? Where should it go?
- The modules list is divided up with a crappy little header per bundle. I couldn't get any color codes to work with the `blessed` `Table` to make them more obvious. Any ideas on getting the colors working?
- The module list no longer displays sub-dependencies. Do we still find this useful? I could never get the sub-dependencies to display for me anyway.
- If we can't change the colors in `Table` and we still want to display sub-dependencies, should we try the `Tree` from `blessed-contrib`? Doesn't seem to have a lot of options for nice columns, though.

Todo:
- Detect inspect mode in the child process
- Use `gzipAsync` concurrently in `inspectpack` to cut down module output time
- Reconnect logic/error handling for child process
- Test against a variety of webpack configs/projects

### CODE REVIEW

**Comment by kenwheeler** [comment]
Outstanding

**Comment by kenwheeler** [comment]
Re questions,

1. Maybe we could live update the title of the Modules box? Like "Modules (Calculating gz output...)"
2. blessed.table({ style.header }) ? Chalk?
3. Since this PR?
4. Hmmm, depends. contrib is kind of janky.

**Comment by tptee** [comment]
Updated `inspectpack` and using the new daemon. Added some nice colored loading/error states for modules/assets. Fixed rebuilds too! (lol)

webpack-dashboard

**Comment by tptee** [comment]
Re: question 3, I couldn't get sub-dependencies to show up in master either. Maybe the README screenshot is out of date? Anyway, my two cents is that the cost of reconstructing the dependency tree from the inspectpack output would be more than the gain of viewing the dependency tree. Thoughts?

**Comment by kenwheeler** [comment]
Bad ass. I don't think subdeps are worth the overhead.

**Comment by Nizam-Ahamed** [comment]
nefahamed@gmail.com

**Comment by tptee** [comment]
@kenwheeler should we cut an alpha for this?

**Comment by kenwheeler** [comment]
yup

**Comment by Nizam-Ahamed** [comment]
nefahamed@gmail.com

**Pull request merged**
