### PR TITLE
Add left/right navigation to move between modules

### PR DESCRIPTION
**Pull request by wapgear**
When we have more than 5 modules (depends on the name size) we can't select it with mouse anymore.
So I think we can use left/right keys to switch between modules.

### CODE REVIEW

**Comment by wapgear** [comment]
@parkerziegler WDYT?

**Comment by ryan-roemer** [comment]
@parkerziegler -- I'm on board with this change and have kicked the tires. Any thoughts before I proceed?

**Comment by wapgear** [comment]
@ryan-roemer any updates? :-)
If need to change anything I could do it on weekend

**Comment by ryan-roemer** [comment]
@wapgear -- Thanks for checking in again! Can you catch this PR up to `master` and just kick the tires one last time with our example of `yarn dev` and make sure things work as expected...

Also, do you know how this deals with overflows (a la https://github.com/FormidableLabs/webpack-dashboard/issues/268 `Display overflows`)? Would this PR fix that issue as well?

I think we may be able to close out https://github.com/FormidableLabs/webpack-dashboard/issues/242 as well `Unable to do pagination on the tabs when many chunk files are showing`

Hopefully we can close out both of these issues with this PR!

**Comment by wapgear** [comment]
@ryan-roemer Not sure about #268 but definitely it solves the #242 issue

Will update with master tomorrow and will test it! Thanks

**Comment by wapgear** [comment]
@ryan-roemer I merged latest master changes and tested it - works just fine.
About issues #242 - yeah, this PR fix it
#268 - unfortunately (or maybe luckily) can't reproduce it on my projects

**Comment by ryan-roemer** [comment]
Released in `webpack-dashboard@3.2.0`

Thanks @wapgear ! 🎉

**Pull request merged**
