### PR TITLE
added progress percentage text to progress box

### PR DESCRIPTION
**Pull request by jamez14**
Added progress indicator text to the "Progress" box that shows a user what percentage of their build is complete. It only shows when progress is between 1 & 99.

screen shot 2016-08-17 at 8 56 53 am

### CODE REVIEW

**Comment by kenwheeler** [comment]
I'll pull this down and give it a spin once I get #50 merged. Thanks!

**Comment by jamez14** [comment]
Looks like the latest version instead opts for only showing the percentage with the minimal "theme". Should I just kill this PR? Or fix the merge conflicts and _always_ show the percentage text?

**Comment by kenwheeler** [comment]
Trying to figure that out. Can you try setContent on the bar itself? I'd really prefer it be on top of the bar, just gotta figure out how.

**Comment by th3fallen** [comment]
just my $.02 could also put the percentage in the label maybe

**Comment by jamez14** [comment]
I'll try some different things out @kenwheeler + @th3fallen

**Comment by jamez14** [comment]
Added percentage text inside the progressbar, for non-minimal version only

screen shot 2016-08-19 at 9 25 32 am

**Comment by kenwheeler** [comment]
That is deeply gangster. Let me give it a spin. Thanks!

**Pull request merged**
