### PR TITLE
Add option to set title of terminal window

### PR DESCRIPTION
**Pull request by bjrn**
Helps identification when running multiple webpack processes.

### CODE REVIEW

**Comment by kenwheeler** [comment]
Thanks!

**Comment by milushov** [comment]
you beat me with this PR 😈 

thanks anyway!

**Comment by milushov** [comment]
@bjrn, btw why you don't bumped the version?

because I have `"0.1.8` version and it doesn't contain this update

**Comment by milushov** [comment]
@kenwheeler could you bump the version and update npm package please? :)

**Comment by bjrn** [comment]
@milushov nice to know that someone else felt a need for that feature too :)

**Pull request merged**
